version: "3.9"

services:
  python:
    container_name: python
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src/
      - ../data:/app/data/
    tty: true
